FROM python:3.9-slim

# Install MLflow and dependencies
RUN pip install mlflow[extras]==2.6.0 boto3==1.28.57

# Create MLflow directory
RUN mkdir -p /mlflow/artifacts

# Set working directory
WORKDIR /mlflow

# Expose MLflow port
EXPOSE 5000

# Default command (overridden in docker-compose)
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"] 